package View;


import Controller.model_chitietthuoc;
import Controller.model_thuoc;
import Model.donThuocChiTiet;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Luong Thanh Long
 */
public class ChiTietDonThuoc extends javax.swing.JFrame {
    private String id= phatthuoc.id2;
    model_chitietthuoc  c= new model_chitietthuoc();
    model_thuoc t= new model_thuoc();
    
    /**
     * Creates new form ChiTietDonThuoc
     */
    public ChiTietDonThuoc() {
        initComponents();
        setVisible(true);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        loaddata();
    }

    public void loaddata()
    {
        
        ResultSet rs=null;
        rs= c.getDataID(id, "maDonThuoc");
        DefaultTableModel model = new DefaultTableModel();
        
        try {
            ResultSetMetaData rsMD = rs.getMetaData();
            int columNumber = rsMD.getColumnCount();
            String[] arr= new String [columNumber];
            for (int i=0;i<columNumber;i++){
                arr[i]=rsMD.getColumnName(i+1);}
            model.setColumnIdentifiers(arr);
            while (rs.next())
            {
                for(int i=0;i<columNumber;i++)
                {
                    arr[i]=rs.getString(i+1);
                }
                model.addRow(arr);
            }
        } catch (SQLException ex) { 
        }   
        jTable1.setModel(model);        
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Số Lượng");

        jButton1.setText("Tìm kiếm thuốc");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Thêm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Sửa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("xóa");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("OK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Reset");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(jButton2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                        .addComponent(jTextField3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5)
                        .addGap(28, 28, 28)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(0, 114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ResultSet rs= null;
        rs=t.getDataID(jTextField1.getText(), "tenThuoc");
        try {
            while (rs.next())
            {
                jTextField2.setText(rs.getString("maThuoc"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(ChiTietDonThuoc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          int soluonggoc=0;
                ResultSet rs= null;
                rs= t.getDataID(jTextField2.getText(), "maThuoc");
        try {
            while (rs.next())
            {
                soluonggoc=rs.getInt("soLuong");
            }
        } catch (SQLException ex) {
            Logger.getLogger(ChiTietDonThuoc.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (soluonggoc > Integer.parseInt(jTextField3.getText()))
        {
        try {
            // TODO add your handling code here:
            
            c.insertID(new donThuocChiTiet(id, jTextField2.getText(), Integer.parseInt(jTextField3.getText())));
            t.updateID1(jTextField2.getText(),Integer.parseInt( jTextField3.getText()));
        } catch (ParseException ex) {
            Logger.getLogger(ChiTietDonThuoc.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ChiTietDonThuoc.class.getName()).log(Level.SEVERE, null, ex);
        }
        loaddata();
        }
        else 
            JOptionPane.showMessageDialog(null, "số lượng Thuốc vượt quá kho",
                     "MESESAGE", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:j
        ResultSet rs= null;
        
        int row;
        row= jTable1.getSelectedRow();
        jTextField2.setText((String) jTable1.getValueAt(row, 2));
        rs= t.getDataID(jTextField2.getText(),"maThuoc");
        try {
            while (rs.next())
            {
                
                jTextField1.setText(rs.getString("tenThuoc"));
            
            }
        } catch (SQLException ex) {
            Logger.getLogger(ChiTietDonThuoc.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTextField3.setText((String) jTable1.getValueAt(row, 3));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int soluong=0;
        ResultSet rs=null;
        rs=t.getDataID(jTextField2.getText(), "maThuoc");
        try {
            while (rs.next())
            {
                soluong = rs.getInt("soLuong");
            }
        } catch (SQLException ex) {
            Logger.getLogger(ChiTietDonThuoc.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        int row;
        row=jTable1.getSelectedRow();
        if(Integer.parseInt((String) jTable1.getValueAt(row, 3))<Integer.parseInt(jTextField3.getText()))
        {
            if(soluong>=-Integer.parseInt((String) jTable1.getValueAt(row, 3))+Integer.parseInt(jTextField3.getText()))
              {
               try {
                  c.updateID((String)jTable1.getValueAt(row, 1),(String) jTextField2.getText(), Integer.parseInt(jTextField3.getText()),(String) jTable1.getValueAt(row, 0));
                  t.updateID1(jTextField2.getText(),-Integer.parseInt((String) jTable1.getValueAt(row, 3))+Integer.parseInt(jTextField3.getText()));
               } catch (ParseException ex) {
                     Logger.getLogger(ChiTietDonThuoc.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                     Logger.getLogger(ChiTietDonThuoc.class.getName()).log(Level.SEVERE, null, ex);
                }
                 loaddata();
              }
               else 
                 {
                    JOptionPane.showMessageDialog(null, "số lượng Thuốc vượt quá kho",
                        "MESESAGE", JOptionPane.ERROR_MESSAGE);
               }
        }
        else if(Integer.parseInt((String) jTable1.getValueAt(row, 3))>Integer.parseInt(jTextField3.getText()))
        {
            try {
                
                c.updateID((String)jTable1.getValueAt(row, 1),(String) jTextField2.getText(), Integer.parseInt(jTextField3.getText()),(String) jTable1.getValueAt(row, 0));
                t.updateID2(jTextField2.getText(),Integer.parseInt((String) jTable1.getValueAt(row, 3))-Integer.parseInt(jTextField3.getText()));
            } catch (ParseException ex) {
                Logger.getLogger(ChiTietDonThuoc.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(ChiTietDonThuoc.class.getName()).log(Level.SEVERE, null, ex);
            }
              loaddata();    
        }
    }//GEN-LAST:event_jButton5ActionPerformed
           
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int row=jTable1.getSelectedRow();
        if (row<0)
        {
             JOptionPane.showMessageDialog(null, "you must chose a row",
                     "delete error", JOptionPane.ERROR_MESSAGE);
             return;
        }
       int select= JOptionPane.showOptionDialog(null, "Are you sure ?", "Delete",0 ,
               JOptionPane.YES_NO_OPTION,null, null, 1);
            if (select==0){
            try {  
                c.deleteID(Integer.parseInt((String) jTable1.getValueAt(row, 0)));
                t.updateID2((String)jTable1.getValueAt(row, 2), Integer.parseInt((String)jTable1.getValueAt(row, 3)));
            } catch (SQLException ex) {
                Logger.getLogger(ChiTietDonThuoc.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(ChiTietDonThuoc.class.getName()).log(Level.SEVERE, null, ex);
            }
                loaddata();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChiTietDonThuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChiTietDonThuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChiTietDonThuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChiTietDonThuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChiTietDonThuoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
