/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.BenhNhan;
import Controller.NhanVien;
import Controller.PhieuKham;
import Controller.QlBenhNhan;
import Controller.QlPhieuKham;
import Model.*;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class FrKhamTongQuat extends javax.swing.JFrame {

    /**
     * Creates new form FrKhamTongQuat
     */
    private Controller.NhanVien nhanVien;
    private ArrayList<PhieuKham> lstBenhNhan;
    private String maBN;
    private String maPK;
    private String maBS;
    private String tenBS;

    public String getTenBS() {
        return tenBS;
    }

    public void setTenBS(String tenBS) {
        this.tenBS = tenBS;
    }
    
    public NhanVien getNhanVien() {
        return nhanVien;
    }

    public void setNhanVien(NhanVien nhanVien) {
        this.nhanVien = nhanVien;
    }
    
    public ArrayList<PhieuKham> getLstBenhNhan() {
        return lstBenhNhan;
    }

    public void setLstBenhNhan(ArrayList<PhieuKham> lstBenhNhan) {
        this.lstBenhNhan = lstBenhNhan;
    }

    public String getMaBN() {
        return maBN;
    }

    public String getMaPK() {
        return maPK;
    }

    public void setMaPK(String maPK) {
        this.maPK = maPK;
    }
    

    public void setMaBN(String maBN) {
        this.maBN = maBN;
    }

    public String getMaBS() {
        return maBS;
    }

    public void setMaBS(String maBS) {
        this.maBS = maBS;
    }
    
    public FrKhamTongQuat() {
        initComponents();
        loadtable();
    }
    public FrKhamTongQuat(String maBS) throws SQLException {
        
        initComponents();
        Model.QuanLyNhanVien qlNhanVien = new Model.QuanLyNhanVien();
        this.setNhanVien(qlNhanVien.timKiemMaNhanVien(maBS));
        this.setMaBS(maBS);
        this.jLabelTenNguoiDangNhap.setText(this.getNhanVien().getHoTen());
        loadtable();
    }
    public void loadtable(){ 
        
        Vector vtColumn=new Vector(); 
        Vector vtRow=new Vector(); 
        Vector vtData=new Vector();
        vtColumn.add("Mã phiếu khám");
        vtColumn.add("Mã bệnh nhân");
        vtColumn.add("Tên bệnh nhân");
        vtColumn.add("Giới tính");
        vtColumn.add("Lý do khám");
        vtColumn.add("Ngày sinh");
        vtColumn.add("Nghề nghiệp");
        vtColumn.add("Tiểu sử bệnh án");
        vtColumn.add("Số điện thoại");
        
        try{
            if(this.lstBenhNhan == null){
                QlPhieuKham qlPhieuKham = new QlPhieuKham();
                this.setLstBenhNhan(qlPhieuKham.timKiem(""));
            }
            if(this.lstBenhNhan.size() > 0){
                for(PhieuKham bn:lstBenhNhan){
                    BenhNhan benhNhan = new BenhNhan();
                    QlBenhNhan qlBenhNhan = new QlBenhNhan();
                    vtRow=new Vector();
                    vtRow.add(bn.getMaPhieuKham());
                    vtRow.add(bn.getMaBenhNhan());
                    vtRow.add(qlBenhNhan.find(bn.getMaBenhNhan()).getTenBenhNhan());
                    vtRow.add(qlBenhNhan.find(bn.getMaBenhNhan()).getGioiTinh());
                    vtRow.add(bn.getLyDoKham()); 
                    vtRow.add(qlBenhNhan.find(bn.getMaBenhNhan()).getNgaySinh());
                    vtRow.add(qlBenhNhan.find(bn.getMaBenhNhan()).getNgheNghiep());
                    vtRow.add(qlBenhNhan.find(bn.getMaBenhNhan()).getTieuSuBenhAn());
                    vtRow.add(qlBenhNhan.find(bn.getMaBenhNhan()).getSoDienThoai());
                    vtData.add(vtRow);                
                } 
            }
            tblDanhSachBenhNhan.setModel(new DefaultTableModel(vtData, vtColumn));
            jLabelSoBenhNhanTrongDanhSach.setText("Có "+getLstBenhNhan().size()+" bản ghi được tìm thấy");
        }catch(Exception ex)
        {
            System.out.println(ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelKhamChuaBenh = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnTiepNhanBenhNhanMoi = new javax.swing.JButton();
        jPanelTimKiemBenhNhan = new javax.swing.JPanel();
        txtMaBenhNhan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTenBenhNhan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbxGioiTinh = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        cbxThang = new javax.swing.JComboBox();
        btnTimKiem = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSachBenhNhan = new javax.swing.JTable();
        thongBao = new javax.swing.JLabel();
        jLabelSoBenhNhanTrongDanhSach = new javax.swing.JLabel();
        btnXemPhienKham = new javax.swing.JButton();
        btnXemBenhNhan = new javax.swing.JButton();
        btnTaoPhienKhamMoi = new javax.swing.JButton();
        jLabelTenPhongKham = new javax.swing.JLabel();
        btnDangXuat = new javax.swing.JButton();
        jLabelTenNguoiDangNhap = new javax.swing.JLabel();
        jPanelDatLichHen = new javax.swing.JPanel();
        jPanelQuanTriHeThong = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bệnh nhân");

        btnTiepNhanBenhNhanMoi.setText("Tiếp nhận bệnh nhân mới");
        btnTiepNhanBenhNhanMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTiepNhanBenhNhanMoiMouseClicked(evt);
            }
        });
        btnTiepNhanBenhNhanMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTiepNhanBenhNhanMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTiepNhanBenhNhanMoi))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnTiepNhanBenhNhanMoi)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelTimKiemBenhNhan.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm bệnh nhân"));

        txtMaBenhNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaBenhNhanActionPerformed(evt);
            }
        });

        jLabel2.setText("Mã bệnh nhân");

        jLabel3.setText("Tên bệnh nhân");

        jLabel4.setText("Giới tính");

        cbxGioiTinh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tất cả", "Nam", "Nữ" }));
        cbxGioiTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxGioiTinhActionPerformed(evt);
            }
        });

        jLabel5.setText("Tìm bệnh nhân theo tháng");

        cbxThang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tất cả", "Tháng 1", "Tháng 2" }));
        cbxThang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbxThangMouseClicked(evt);
            }
        });

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimKiemMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelTimKiemBenhNhanLayout = new javax.swing.GroupLayout(jPanelTimKiemBenhNhan);
        jPanelTimKiemBenhNhan.setLayout(jPanelTimKiemBenhNhanLayout);
        jPanelTimKiemBenhNhanLayout.setHorizontalGroup(
            jPanelTimKiemBenhNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTimKiemBenhNhanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTimKiemBenhNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cbxGioiTinh, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTenBenhNhan, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaBenhNhan, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxThang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTimKiemBenhNhanLayout.setVerticalGroup(
            jPanelTimKiemBenhNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTimKiemBenhNhanLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtMaBenhNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtTenBenhNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(cbxGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(cbxThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnTimKiem)
                .addContainerGap())
        );

        tblDanhSachBenhNhan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Họ tên", "Tuổi", "Số điện thoại", "Giới tính", "Thời gian tiếp nhận", "Ghi chú"
            }
        ));
        tblDanhSachBenhNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachBenhNhanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblDanhSachBenhNhanMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhSachBenhNhan);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(thongBao)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(thongBao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabelSoBenhNhanTrongDanhSach.setText("Có 0 mục được tìm thấy ");

        btnXemPhienKham.setText("Xem phiên khám");
        btnXemPhienKham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXemPhienKhamMouseClicked(evt);
            }
        });
        btnXemPhienKham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemPhienKhamActionPerformed(evt);
            }
        });

        btnXemBenhNhan.setText("Xem bệnh nhân");
        btnXemBenhNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXemBenhNhanMouseClicked(evt);
            }
        });

        btnTaoPhienKhamMoi.setText("Tạo phiên khám mới");
        btnTaoPhienKhamMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTaoPhienKhamMoiMouseClicked(evt);
            }
        });

        jLabelTenPhongKham.setText("Phòng khám XYZ");

        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDangXuatMouseClicked(evt);
            }
        });

        jLabelTenNguoiDangNhap.setText("Tên người đăng nhập");

        javax.swing.GroupLayout jPanelKhamChuaBenhLayout = new javax.swing.GroupLayout(jPanelKhamChuaBenh);
        jPanelKhamChuaBenh.setLayout(jPanelKhamChuaBenhLayout);
        jPanelKhamChuaBenhLayout.setHorizontalGroup(
            jPanelKhamChuaBenhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelKhamChuaBenhLayout.createSequentialGroup()
                .addComponent(jPanelTimKiemBenhNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelKhamChuaBenhLayout.createSequentialGroup()
                .addGroup(jPanelKhamChuaBenhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelKhamChuaBenhLayout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addComponent(jLabelSoBenhNhanTrongDanhSach)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTaoPhienKhamMoi)
                        .addGap(18, 18, 18)
                        .addComponent(btnXemBenhNhan)
                        .addGap(18, 18, 18)
                        .addComponent(btnXemPhienKham))
                    .addGroup(jPanelKhamChuaBenhLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelTenPhongKham)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelTenNguoiDangNhap)
                        .addGap(18, 18, 18)
                        .addComponent(btnDangXuat)))
                .addContainerGap())
        );
        jPanelKhamChuaBenhLayout.setVerticalGroup(
            jPanelKhamChuaBenhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKhamChuaBenhLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelKhamChuaBenhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelTimKiemBenhNhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelKhamChuaBenhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSoBenhNhanTrongDanhSach)
                    .addComponent(btnXemPhienKham)
                    .addComponent(btnXemBenhNhan)
                    .addComponent(btnTaoPhienKhamMoi))
                .addGap(46, 46, 46)
                .addGroup(jPanelKhamChuaBenhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTenPhongKham)
                    .addComponent(btnDangXuat)
                    .addComponent(jLabelTenNguoiDangNhap))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Khám chữa bệnh", jPanelKhamChuaBenh);

        javax.swing.GroupLayout jPanelDatLichHenLayout = new javax.swing.GroupLayout(jPanelDatLichHen);
        jPanelDatLichHen.setLayout(jPanelDatLichHenLayout);
        jPanelDatLichHenLayout.setHorizontalGroup(
            jPanelDatLichHenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 941, Short.MAX_VALUE)
        );
        jPanelDatLichHenLayout.setVerticalGroup(
            jPanelDatLichHenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Tiếp nhận và đặt lịch hẹn", jPanelDatLichHen);

        javax.swing.GroupLayout jPanelQuanTriHeThongLayout = new javax.swing.GroupLayout(jPanelQuanTriHeThong);
        jPanelQuanTriHeThong.setLayout(jPanelQuanTriHeThongLayout);
        jPanelQuanTriHeThongLayout.setHorizontalGroup(
            jPanelQuanTriHeThongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 941, Short.MAX_VALUE)
        );
        jPanelQuanTriHeThongLayout.setVerticalGroup(
            jPanelQuanTriHeThongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Quản trị hệ thống", jPanelQuanTriHeThong);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTiepNhanBenhNhanMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTiepNhanBenhNhanMoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTiepNhanBenhNhanMoiActionPerformed

    private void txtMaBenhNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaBenhNhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaBenhNhanActionPerformed

    private void cbxGioiTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxGioiTinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxGioiTinhActionPerformed

    private void btnXemPhienKhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemPhienKhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXemPhienKhamActionPerformed

    private void cbxThangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxThangMouseClicked
        
    }//GEN-LAST:event_cbxThangMouseClicked

    private void btnTimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimKiemMouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            String maBenhNhan = txtMaBenhNhan.getText();
            String tenBenhNhan = txtTenBenhNhan.getText();
            String gioiTinh = cbxGioiTinh.getSelectedItem().toString();
            String thang = cbxThang.getSelectedItem().toString();
            thongBao.setText("");
            
            QlPhieuKham qlPhieuKham = new QlPhieuKham();
            int soBanGhi = qlPhieuKham.timKiem(maBenhNhan).size();
            if(soBanGhi >= 1){
                this.setLstBenhNhan(qlPhieuKham.timKiem(maBenhNhan));
                thongBao.setText("");
            }
            else
            {
                thongBao.setText("Không tìm thấy kết quả nào");
            }
            
            loadtable();
        } catch (SQLException ex) {
            Logger.getLogger(FrKhamTongQuat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTimKiemMouseClicked

    private void btnTaoPhienKhamMoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTaoPhienKhamMoiMouseClicked
        // TODO add your handling code here:
        if(!getMaBN().isEmpty() && !getMaPK().isEmpty() && !getMaBS().isEmpty()){
            try {
                FrPhienKhamMoi frPKM = new FrPhienKhamMoi(getMaBN(), getMaPK(), getMaBS());
                frPKM.show();
                this.setVisible(false);
            } catch (SQLException ex) {
                Logger.getLogger(FrKhamTongQuat.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(FrKhamTongQuat.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_btnTaoPhienKhamMoiMouseClicked

    private void tblDanhSachBenhNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachBenhNhanMouseClicked
        // TODO add your handling code here:
        int Row = tblDanhSachBenhNhan.getSelectedRow();
        String maPK = (String)tblDanhSachBenhNhan.getValueAt(Row, 0);
        String ids = (String) tblDanhSachBenhNhan.getValueAt(Row, 1);
        this.setMaBN(ids);
        this.setMaPK(maPK);
    }//GEN-LAST:event_tblDanhSachBenhNhanMouseClicked

    private void tblDanhSachBenhNhanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachBenhNhanMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tblDanhSachBenhNhanMouseEntered

    private void btnXemBenhNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXemBenhNhanMouseClicked
        try {
            // TODO add your handling code here:
            FrXemThongTinBenhNhan frXemBN = new FrXemThongTinBenhNhan(this.getMaBN(), this.getMaPK(),this.getNhanVien().getHoTen(), this.getMaBS());
            frXemBN.show();
        } catch (SQLException ex) {
            Logger.getLogger(FrKhamTongQuat.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(FrKhamTongQuat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnXemBenhNhanMouseClicked

    private void btnXemPhienKhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXemPhienKhamMouseClicked
        try {
            // TODO add your handling code here:
            FrDanhSachPhienKham frDSPK = new FrDanhSachPhienKham(this.getMaBN(), this.getMaPK(), this.getMaBS());
            frDSPK.show();
        } catch (SQLException ex) {
            Logger.getLogger(FrKhamTongQuat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnXemPhienKhamMouseClicked

    private void btnTiepNhanBenhNhanMoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTiepNhanBenhNhanMoiMouseClicked
        try {
            // TODO add your handling code here:
            FrTiepNhanBenhNhanMoi frThemMoi = new FrTiepNhanBenhNhanMoi(this.getMaBS());
            frThemMoi.show();
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(FrKhamTongQuat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTiepNhanBenhNhanMoiMouseClicked

    private void btnDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangXuatMouseClicked
        // TODO add your handling code here:
        Jfr_login login = new Jfr_login();
        login.show();
        this.dispose();
    }//GEN-LAST:event_btnDangXuatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrKhamTongQuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrKhamTongQuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrKhamTongQuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrKhamTongQuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrKhamTongQuat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnTaoPhienKhamMoi;
    private javax.swing.JButton btnTiepNhanBenhNhanMoi;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXemBenhNhan;
    private javax.swing.JButton btnXemPhienKham;
    private javax.swing.JComboBox cbxGioiTinh;
    private javax.swing.JComboBox cbxThang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelSoBenhNhanTrongDanhSach;
    private javax.swing.JLabel jLabelTenNguoiDangNhap;
    private javax.swing.JLabel jLabelTenPhongKham;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelDatLichHen;
    private javax.swing.JPanel jPanelKhamChuaBenh;
    private javax.swing.JPanel jPanelQuanTriHeThong;
    private javax.swing.JPanel jPanelTimKiemBenhNhan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblDanhSachBenhNhan;
    private javax.swing.JLabel thongBao;
    private javax.swing.JTextField txtMaBenhNhan;
    private javax.swing.JTextField txtTenBenhNhan;
    // End of variables declaration//GEN-END:variables
}
