/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.NhanVien;
import Controller.QlBenhNhan;
import Controller.QlPhieuKham;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class FrTiepNhanBenhNhanMoi extends javax.swing.JFrame {

    /**
     * Creates new form FrTiepNhanBenhNhanMoi
     */
    private Controller.NhanVien nhanVien;

    public NhanVien getNhanVien() {
        return nhanVien;
    }

    public void setNhanVien(NhanVien nhanVien) {
        this.nhanVien = nhanVien;
    }
    
    public FrTiepNhanBenhNhanMoi() throws SQLException {
        initComponents();
        loadCombobox();
    }
    public FrTiepNhanBenhNhanMoi(String maNV) throws SQLException {
        initComponents();
        loadData(maNV);
        loadCombobox();
    }
    
    public void loadData(String maNV) throws SQLException{
        Model.QuanLyNhanVien qlNhanVien = new Model.QuanLyNhanVien();
        this.setNhanVien(qlNhanVien.timKiemMaNhanVien(maNV));
        this.jLabelAddTenNguoiDangNhap.setText(this.getNhanVien().getHoTen());
    }
    public void loadCombobox() throws SQLException{
        Model.QuanLyNhanVien qlNhanVien = new Model.QuanLyNhanVien();
        ArrayList<Controller.NhanVien> lstBacSi = new ArrayList<>();
        lstBacSi = qlNhanVien.findBacSi();
        for(Controller.NhanVien bacSi:lstBacSi){
            String tenBS_Ma = bacSi.getHoTen() + "_" + bacSi.getMaNhanVien();
            this.cbxTenBacSi.addItem(tenBS_Ma);
            //this.cbxTenBacSi.setSelectedItem(tenBS_Ma);
        }
    }
    
    /*public void LoadComboBox2()
        {
            DataTable dt = new DataTable();
            connection.Open();
            try
            {
                SqlDataAdapter da = new SqlDataAdapter("Select TenKhoa From Khoa", connection);
                da.Fill(dt);
                connection.Close();
            }
            catch(Exception ex)
            {
                throw new Exception("Error " + ex.ToString());
            }

            try
        {
            cbbTenKhoa.DataSource = dt;
            cbbTenKhoa.DisplayMember = "TenKhoa";
            cbbTenKhoa.ValueMember = "TenKhoa";
        }
        catch(Exception ex)
        {
            MessageBox.Show("Có lỗi khi load dữ liệu!\n", ex.ToString());
        }
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtAddMaBenhNhan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAddHoTen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbxAddGioiTinh = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        txtAddNgaySinh = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNgheNghiep = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbxAddTinhTrangHonNhan = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        txtAddDiaChi = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtAddSoDienThoai = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAddLyDoKham = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAddGhiChu = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        txtAddMaPhieuKham = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cbxTenBacSi = new javax.swing.JComboBox();
        btnAddTao = new javax.swing.JButton();
        btnAddReset = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtAddCMND = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAddTienSuBenhAn = new javax.swing.JTextArea();
        jLabelAddTenNguoiDangNhap = new javax.swing.JLabel();
        btnAddDangXuat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tiếp nhận bệnh nhân mới ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tiếp nhận mới", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel1.setText("Mã bệnh nhân");

        jLabel2.setText("Họ tên");

        jLabel3.setText("Giới tính");

        cbxAddGioiTinh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nam", "Nữ" }));

        jLabel4.setText("Ngày sinh");

        jLabel5.setText("Nghề nghiệp");

        jLabel6.setText("Tình trạng hôn nhân");

        cbxAddTinhTrangHonNhan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Độc thân", "Đã kết hôn" }));

        jLabel7.setText("Địa chỉ");

        jLabel12.setText("Số điện thoại");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAddMaBenhNhan)
                    .addComponent(txtAddHoTen)
                    .addComponent(cbxAddGioiTinh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAddNgaySinh)
                    .addComponent(txtNgheNghiep)
                    .addComponent(cbxAddTinhTrangHonNhan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAddDiaChi)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel12))
                        .addGap(0, 167, Short.MAX_VALUE))
                    .addComponent(txtAddSoDienThoai))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAddMaBenhNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAddHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxAddGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAddNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(txtNgheNghiep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxAddTinhTrangHonNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAddDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(txtAddSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tình trạng tiếp nhận", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel9.setText("Lý do khám");

        txtAddLyDoKham.setColumns(20);
        txtAddLyDoKham.setRows(5);
        jScrollPane2.setViewportView(txtAddLyDoKham);

        jLabel10.setText("Ghi chú (nếu có)");

        txtAddGhiChu.setColumns(20);
        txtAddGhiChu.setRows(5);
        jScrollPane3.setViewportView(txtAddGhiChu);

        jLabel8.setText("Mã phiếu khám");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtAddMaPhieuKham))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAddMaPhieuKham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel11.setText("Bác sĩ khám");

        btnAddTao.setText("Tạo");
        btnAddTao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddTaoMouseClicked(evt);
            }
        });

        btnAddReset.setText("Reset");
        btnAddReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddResetMouseClicked(evt);
            }
        });

        jLabel13.setText("Số CMND");

        jLabel14.setText("Tiểu sử bệnh án");

        txtAddTienSuBenhAn.setColumns(20);
        txtAddTienSuBenhAn.setRows(5);
        jScrollPane4.setViewportView(txtAddTienSuBenhAn);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAddCMND)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAddCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelAddTenNguoiDangNhap.setText("Tên người đăng nhập");

        btnAddDangXuat.setText("Đăng xuất");
        btnAddDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddDangXuatMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelAddTenNguoiDangNhap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAddDangXuat)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxTenBacSi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAddTao, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                                .addComponent(btnAddReset, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxTenBacSi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddTao)
                            .addComponent(btnAddReset)
                            .addComponent(jLabelAddTenNguoiDangNhap)
                            .addComponent(btnAddDangXuat))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddResetMouseClicked
        // TODO add your handling code here:
        txtAddMaBenhNhan.setText("");
        txtAddMaPhieuKham.setText("");
        txtAddHoTen.setText("");
        txtAddNgaySinh.setText("");
        txtNgheNghiep.setText("");
        txtAddDiaChi.setText("");
        txtAddTienSuBenhAn.setText("");
        txtAddLyDoKham.setText("");
        txtAddSoDienThoai.setText("");
        txtAddGhiChu.setText("");
        txtAddCMND.setText("");
        cbxTenBacSi.setSelectedItem("");
    }//GEN-LAST:event_btnAddResetMouseClicked

    private void btnAddTaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddTaoMouseClicked
        try {
            // TODO add your handling code here:
            String maBenhNhan = txtAddMaBenhNhan.getText();
            String tenBN = txtAddHoTen.getText();
            String gioiTinh = cbxAddGioiTinh.getSelectedItem().toString();
            String NS = txtAddNgaySinh.getText();
            SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
            Date ngaySinh = formatter.parse(NS);
            String ngheNghiep = txtNgheNghiep.getText();
            int tinhTrangHonNhan;
            if(cbxAddTinhTrangHonNhan.getSelectedItem().toString().equals("Độc thân"))
                tinhTrangHonNhan = 0;
            else
                tinhTrangHonNhan = 1;
            String diaChi = txtAddDiaChi.getText();
            String tieuSuBenhAn = txtAddTienSuBenhAn.getText();
            String soDienThoai = txtAddSoDienThoai.getText();
            String soCMND = txtAddCMND.getText();
            Controller.BenhNhan benhNhan = new Controller.BenhNhan(maBenhNhan, tenBN, gioiTinh, ngaySinh, ngheNghiep, tinhTrangHonNhan, diaChi, tieuSuBenhAn, soDienThoai, soCMND);
            QlBenhNhan qlBenhNhan = new QlBenhNhan();
            Boolean rs2, rs = qlBenhNhan.themMoiBenhNhan(benhNhan);
            String maPhieuKham = txtAddMaPhieuKham.getText();
            String lsDoKham = txtAddLyDoKham.getText();
            String ghiChu = txtAddGhiChu.getText();
            String tenBacSi = cbxTenBacSi.getSelectedItem().toString();
            Controller.QlPhieuKham qlPhieuKham = new Controller.QlPhieuKham();
            Controller.PhieuKham pk = new Controller.PhieuKham(maPhieuKham, this.getNhanVien().getMaNhanVien(), maBenhNhan, lsDoKham, ghiChu, tenBacSi, 0.0);
            rs2 = qlPhieuKham.themMoiPhieuKham(pk);
            if(rs2){
                JOptionPane.showMessageDialog(rootPane, "Lưu thông tin bệnh nhân thành công");
                //FrXemThongTinBenhNhan thongTin = new FrXemThongTinBenhNhan(txtAddMaBenhNhan.getText(), txtAddMaPhieuKham.getText(), cbxTenBacSi.getSelectedItem().toString(), this.getNhanVien().getMaNhanVien());
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Lưu thông tin bệnh nhân không thành công");

            }
            this.setVisible(false);
            FrKhamTongQuat frTQ = new FrKhamTongQuat(this.getNhanVien().getMaNhanVien());
            frTQ.show();
            
        } catch (ParseException ex) {
            Logger.getLogger(FrTiepNhanBenhNhanMoi.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FrTiepNhanBenhNhanMoi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddTaoMouseClicked

    private void btnAddDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddDangXuatMouseClicked
        // TODO add your handling code here:
        Jfr_login login = new Jfr_login();
        login.show();
        this.dispose();
    }//GEN-LAST:event_btnAddDangXuatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrTiepNhanBenhNhanMoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrTiepNhanBenhNhanMoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrTiepNhanBenhNhanMoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrTiepNhanBenhNhanMoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrTiepNhanBenhNhanMoi().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FrTiepNhanBenhNhanMoi.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDangXuat;
    private javax.swing.JButton btnAddReset;
    private javax.swing.JButton btnAddTao;
    private javax.swing.JComboBox cbxAddGioiTinh;
    private javax.swing.JComboBox cbxAddTinhTrangHonNhan;
    private javax.swing.JComboBox cbxTenBacSi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAddTenNguoiDangNhap;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField txtAddCMND;
    private javax.swing.JTextField txtAddDiaChi;
    private javax.swing.JTextArea txtAddGhiChu;
    private javax.swing.JTextField txtAddHoTen;
    private javax.swing.JTextArea txtAddLyDoKham;
    private javax.swing.JTextField txtAddMaBenhNhan;
    private javax.swing.JTextField txtAddMaPhieuKham;
    private javax.swing.JTextField txtAddNgaySinh;
    private javax.swing.JTextField txtAddSoDienThoai;
    private javax.swing.JTextArea txtAddTienSuBenhAn;
    private javax.swing.JTextField txtNgheNghiep;
    // End of variables declaration//GEN-END:variables
}
