/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.BenhNhan;
import Controller.NhanVien;
import Controller.PhieuKham;
import Controller.QlBenhNhan;
import Controller.QlPhieuKham;
import Model.*;
import Model.QuanLyNhanVien;
import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class FrXemThongTinBenhNhan extends javax.swing.JFrame {

    /**
     * Creates new form FrXemThongTinBenhNhan
     */
    private BenhNhan benhNhan;
    private PhieuKham phieuKham;
    private NhanVien nhanVien;
    private NhanVien userName;
    private String tenBS;

    public NhanVien getUserName() {
        return userName;
    }

    public void setUserName(NhanVien userName) {
        this.userName = userName;
    }
    
    public String getTenBS() {
        return tenBS;
    }

    public void setTenBS(String tenBS) {
        this.tenBS = tenBS;
    }
    
    public BenhNhan getBenhNhan() {
        return benhNhan;
    }

    public void setBenhNhan(BenhNhan benhNhan) {
        this.benhNhan = benhNhan;
    }

    public PhieuKham getPhieuKham() {
        return phieuKham;
    }

    public void setPhieuKham(PhieuKham phieuKham) {
        this.phieuKham = phieuKham;
    }

    public NhanVien getNhanVien() {
        return nhanVien;
    }

    public void setNhanVien(NhanVien nhanVien) {
        this.nhanVien = nhanVien;
    }
    
    public FrXemThongTinBenhNhan() {
        initComponents();
    }
    
    public FrXemThongTinBenhNhan(String maBN, String maPK, String tenBS, String maBS) throws SQLException, ParseException {
        initComponents();
        loadData(maBN, maPK, tenBS, maBS);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
    
    public void loadData(String maBN, String maPK, String tenBS, String maBS) throws SQLException, ParseException{
        QlBenhNhan qlBenhNhan = new QlBenhNhan();
        QlPhieuKham qlPhieuKham = new QlPhieuKham();
        QuanLyNhanVien qlNhanVien = new QuanLyNhanVien();
        this.setUserName(qlNhanVien.timKiemMaNhanVien(maBS));
        this.jLabelShowTenDangNhap.setText(this.getUserName().getHoTen());
        this.setBenhNhan(qlBenhNhan.find(maBN));
        this.setPhieuKham(qlPhieuKham.timKiemId(maPK));
        this.setTenBS(tenBS);
        String maNV = getPhieuKham().getMaNhanVien();
        NhanVien nv = qlNhanVien.timKiemMaNhanVien(maNV);
        this.setNhanVien(nv);
        
        txtShowMaBenhNhan.setText(getBenhNhan().getMaBenhNhan());
        txtShowHoTen.setText(getBenhNhan().getTenBenhNhan());
        
        txtGioiTinh.setText(getBenhNhan().getGioiTinh());
        if(getBenhNhan().getTinhTrangHonNhan() == 0)
            txtTinhTrangHonNhan.setText("Độc thân");
        else
            txtTinhTrangHonNhan.setText("Đã kết hôn");
        //txtTinhTrangHonNhan.setText((getBenhNhan().getTinhTrangHonNhan() == 0)? "Độc thân":"Đã kết hôn");
        txtShowDiaChi.setText(getBenhNhan().getDiaChi());
        txtShowTieuSuBenhAn.setText(getBenhNhan().getTieuSuBenhAn());
        txtShowSoDienThoai.setText(getBenhNhan().getSoDienThoai());
        txtShowLyDoKham.setText(getPhieuKham().getLyDoKham());
        txtShowGhiChu.setText(getPhieuKham().getGhiChu());
        txtShowBacSiKham.setText(getPhieuKham().getTenBacSi());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtShowMaBenhNhan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtShowHoTen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtShowDiaChi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtShowTieuSuBenhAn = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        txtShowSoDienThoai = new javax.swing.JTextField();
        jLabelShowTenPhongKham = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtShowLyDoKham = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtShowGhiChu = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        txtShowBacSiKham = new javax.swing.JTextField();
        btnShowCapNhatThongTin = new javax.swing.JButton();
        btnXuatFile = new javax.swing.JButton();
        btnShowDangXuat = new javax.swing.JButton();
        jLabelShowTenDangNhap = new javax.swing.JLabel();
        txtGioiTinh = new javax.swing.JTextField();
        txtTinhTrangHonNhan = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin bệnh nhân", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel1.setText("Mã bệnh nhân");

        jLabel2.setText("Họ tên");

        txtShowHoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtShowHoTenActionPerformed(evt);
            }
        });

        jLabel3.setText("Giới tính");

        jLabel4.setText("Tình trạng hôn nhân");

        jLabel5.setText("Địa chỉ");

        jLabel6.setText("Tiền sử bệnh án");

        txtShowTieuSuBenhAn.setColumns(20);
        txtShowTieuSuBenhAn.setRows(5);
        jScrollPane1.setViewportView(txtShowTieuSuBenhAn);

        jLabel7.setText("Số điện thoại");

        jLabelShowTenPhongKham.setText("Phòng khám XYZ");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tình trạng bệnh", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel9.setText("Lý do khám bệnh");

        txtShowLyDoKham.setColumns(20);
        txtShowLyDoKham.setRows(5);
        jScrollPane2.setViewportView(txtShowLyDoKham);

        jLabel10.setText("Ghi chú khám bệnh");

        txtShowGhiChu.setColumns(20);
        txtShowGhiChu.setRows(5);
        jScrollPane3.setViewportView(txtShowGhiChu);

        jLabel11.setText("Bác sĩ");

        btnShowCapNhatThongTin.setText("Cập nhật thông tin");
        btnShowCapNhatThongTin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowCapNhatThongTinMouseClicked(evt);
            }
        });
        btnShowCapNhatThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowCapNhatThongTinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addComponent(txtShowBacSiKham)
                    .addComponent(btnShowCapNhatThongTin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(txtShowBacSiKham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btnShowCapNhatThongTin)
                .addContainerGap())
        );

        btnXuatFile.setText("In phiếu");
        btnXuatFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXuatFileMouseClicked(evt);
            }
        });

        btnShowDangXuat.setText("Đăng xuất");
        btnShowDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowDangXuatMouseClicked(evt);
            }
        });

        jLabelShowTenDangNhap.setText("Tên Người đăng nhập");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(txtShowMaBenhNhan)
                            .addComponent(jLabel2)
                            .addComponent(txtShowHoTen)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(txtShowDiaChi)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                            .addComponent(jLabel7)
                            .addComponent(txtShowSoDienThoai)
                            .addComponent(txtGioiTinh)
                            .addComponent(txtTinhTrangHonNhan))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnXuatFile))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelShowTenPhongKham)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelShowTenDangNhap)
                        .addGap(18, 18, 18)
                        .addComponent(btnShowDangXuat)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnXuatFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtShowMaBenhNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtShowHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTinhTrangHonNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtShowDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtShowSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelShowTenPhongKham)
                    .addComponent(btnShowDangXuat)
                    .addComponent(jLabelShowTenDangNhap))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtShowHoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtShowHoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtShowHoTenActionPerformed

    private void btnShowCapNhatThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowCapNhatThongTinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowCapNhatThongTinActionPerformed

    private void btnShowCapNhatThongTinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowCapNhatThongTinMouseClicked
        try {
            // TODO add your handling code here:
            String maBN = txtShowMaBenhNhan.getText();
            String tenBN = txtShowHoTen.getText();
            String gioiTinh = txtGioiTinh.getText();
            int tinhTrangHN;
            tinhTrangHN = (txtTinhTrangHonNhan.getText().equals("Độc thân") == true)?0:1;
            String diaChi = txtShowDiaChi.getText();
            String tieuSu = txtShowTieuSuBenhAn.getText();
            String soDienThoai = txtShowSoDienThoai.getText();
            if(tenBN.equals(this.getBenhNhan().getTenBenhNhan()) == false
                    || gioiTinh.equals(this.getBenhNhan().getGioiTinh()) == false
                    || tinhTrangHN != this.getBenhNhan().getTinhTrangHonNhan()
                    || diaChi.equals(this.getBenhNhan().getDiaChi()) == false
                    || tieuSu.equals(this.getBenhNhan().getTieuSuBenhAn()) == false
                    || soDienThoai.equals(this.getBenhNhan().getSoDienThoai()) == false){
                try {
                    this.getBenhNhan().setTenBenhNhan(tenBN);
                    this.getBenhNhan().setGioiTinh(gioiTinh);
                    this.getBenhNhan().setTinhTrangHonNhan(tinhTrangHN);
                    this.getBenhNhan().setDiaChi(diaChi);
                    this.getBenhNhan().setTieuSuBenhAn(tieuSu);
                    this.getBenhNhan().setSoDienThoai(soDienThoai);
                    QlBenhNhan qlBenhNhan = new QlBenhNhan();
                    Boolean rs = qlBenhNhan.update(this.getBenhNhan());
                } catch (SQLException ex) {
                    Logger.getLogger(FrXemThongTinBenhNhan.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
            String lyDo = txtShowLyDoKham.getText();
            String ghiChu = txtShowGhiChu.getText();
            String tenBS = txtShowBacSiKham.getText();
            
            if(lyDo.equals(this.getPhieuKham().getLyDoKham()) == false
                    || ghiChu.equals(this.getPhieuKham().getGhiChu()) == false
                    || tenBS.equals(this.getPhieuKham().getTenBacSi()) == false){
                try {
                    this.getPhieuKham().setLyDoKham(lyDo);
                    this.getPhieuKham().setGhiChu(ghiChu);
                    this.getPhieuKham().setTenBacSi(tenBS);
                    QlPhieuKham qlPhieuKham = new QlPhieuKham();
                    Boolean rs2 = qlPhieuKham.update(this.getPhieuKham());
                } catch (SQLException ex) {
                    Logger.getLogger(FrXemThongTinBenhNhan.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            JOptionPane.showMessageDialog(rootPane, "Chỉnh sửa thông tin bệnh nhân thành công");
            this.dispose();
            FrKhamTongQuat frTongQuat = new FrKhamTongQuat(this.getNhanVien().getMaNhanVien());
            frTongQuat.show();
        } catch (SQLException ex) {
            Logger.getLogger(FrXemThongTinBenhNhan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnShowCapNhatThongTinMouseClicked

    private void btnXuatFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXuatFileMouseClicked
        try {
            // TODO add your handling code here:
            String tenFile = "Thông tin bệnh nhân_"+txtShowHoTen.getText();
            String tenPhongKham = "Phòng khám HUST";
            ArrayList<String> noiDung = new ArrayList<>();
            String maBenhNhan = "Mã bệnh nhân: "+txtShowMaBenhNhan.getText();
            String tenBenhNhan = "Tên bệnh nhân: "+txtShowHoTen.getText();
            String gioiTinh = txtGioiTinh.getText() + " ---- " + txtTinhTrangHonNhan.getText();
            String diaChi = "Địa chỉ" + txtShowDiaChi.getText();
            String tieuSu = "Tiểu sử bệnh án" + txtShowTieuSuBenhAn.getText();
            String sdt = "Số điện thoại: " + txtShowSoDienThoai.getText();
            String lyDoKham = "Triệu chứng: " + txtShowLyDoKham.getText();
            String ghiChu = "Ghi chú: " + txtShowGhiChu.getText();
            String nhanVienThucHien = "Tên bác sĩ: " + txtShowBacSiKham.getText();
            Controller.XuatFile xuatFile = new Controller.XuatFile();
            xuatFile.export(tenFile, tenPhongKham, noiDung);
        } catch (IOException ex) {
            Logger.getLogger(FrXemThongTinBenhNhan.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FrXemThongTinBenhNhan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnXuatFileMouseClicked

    private void btnShowDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowDangXuatMouseClicked
        // TODO add your handling code here:
        Jfr_login login = new Jfr_login();
        login.show();
        this.dispose();
    }//GEN-LAST:event_btnShowDangXuatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrXemThongTinBenhNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrXemThongTinBenhNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrXemThongTinBenhNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrXemThongTinBenhNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrXemThongTinBenhNhan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnShowCapNhatThongTin;
    private javax.swing.JButton btnShowDangXuat;
    private javax.swing.JButton btnXuatFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelShowTenDangNhap;
    private javax.swing.JLabel jLabelShowTenPhongKham;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField txtGioiTinh;
    private javax.swing.JTextField txtShowBacSiKham;
    private javax.swing.JTextField txtShowDiaChi;
    private javax.swing.JTextArea txtShowGhiChu;
    private javax.swing.JTextField txtShowHoTen;
    private javax.swing.JTextArea txtShowLyDoKham;
    private javax.swing.JTextField txtShowMaBenhNhan;
    private javax.swing.JTextField txtShowSoDienThoai;
    private javax.swing.JTextArea txtShowTieuSuBenhAn;
    private javax.swing.JTextField txtTinhTrangHonNhan;
    // End of variables declaration//GEN-END:variables
}
