/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Connection.DBConnection;
import Controller.Printer;
import Controller.c_XetNghiem;
import Model.m_XetNghiem;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Controller.c_XetNghiem;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author user
 */
public class Jfr_phieuXetNghiem extends javax.swing.JFrame {

    /**
     * Creates new form Jfr_phieuXetNghiem
     */
    String maNhanVien = Jfr_login.maNhanVien;
    
    public Jfr_phieuXetNghiem() {
        initComponents();
        PreparedStatement ps = DBConnection.ThucThiTruyVan("select * from nhanvien "
                + "where maNhanVien like '"+maNhanVien+"'");
        try{
            ResultSet rs = ps.executeQuery();
            rs.next();
            this.lbNhanVien.setText(rs.getString(5)+": "+rs.getString(2)+" - Mã NV: "+maNhanVien);
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex, "Lỗi !",0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        pnPhieuKhamChiTiet = new javax.swing.JPanel();
        btShow = new javax.swing.JButton();
        txtMaBenhNhan = new javax.swing.JTextField();
        txtCMT = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtChiSoSucKhoe = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtKetLuan = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtYeuCau = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        btHoanThanh = new javax.swing.JButton();
        btReset = new javax.swing.JButton();
        lbNhanVien = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btHome = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnPhieuKhamChiTiet.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Phiếu Khám Chi Tiết", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 16))); // NOI18N

        btShow.setBackground(new java.awt.Color(204, 204, 255));
        btShow.setText("Hiển Thị");
        btShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btShowActionPerformed(evt);
            }
        });

        txtMaBenhNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaBenhNhanActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Mã BN : ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("CMT :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Họ Tên : ");

        txtChiSoSucKhoe.setColumns(20);
        txtChiSoSucKhoe.setRows(5);
        jScrollPane1.setViewportView(txtChiSoSucKhoe);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Chỉ Số");

        txtKetLuan.setColumns(20);
        txtKetLuan.setRows(5);
        jScrollPane2.setViewportView(txtKetLuan);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Kết Luận :");

        txtYeuCau.setColumns(20);
        txtYeuCau.setRows(5);
        jScrollPane3.setViewportView(txtYeuCau);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Yêu Cầu :");

        btHoanThanh.setBackground(new java.awt.Color(204, 204, 255));
        btHoanThanh.setText("Hoàn Thành");
        btHoanThanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHoanThanhActionPerformed(evt);
            }
        });

        btReset.setBackground(new java.awt.Color(204, 204, 255));
        btReset.setText("Reset");
        btReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetActionPerformed(evt);
            }
        });

        lbNhanVien.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbNhanVien.setText("jLabel7");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Sức Khỏe :");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        btHome.setBackground(new java.awt.Color(204, 204, 255));
        btHome.setText("Home");
        btHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHomeActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setText("Quản Lý");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnPhieuKhamChiTietLayout = new javax.swing.GroupLayout(pnPhieuKhamChiTiet);
        pnPhieuKhamChiTiet.setLayout(pnPhieuKhamChiTietLayout);
        pnPhieuKhamChiTietLayout.setHorizontalGroup(
            pnPhieuKhamChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPhieuKhamChiTietLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnPhieuKhamChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnPhieuKhamChiTietLayout.createSequentialGroup()
                        .addGroup(pnPhieuKhamChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnPhieuKhamChiTietLayout.createSequentialGroup()
                                .addComponent(btHome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btHoanThanh))
                            .addGroup(pnPhieuKhamChiTietLayout.createSequentialGroup()
                                .addComponent(btShow, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnPhieuKhamChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(14, 14, 14)))
                        .addGroup(pnPhieuKhamChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane2)
                            .addComponent(txtMaBenhNhan, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                            .addComponent(txtCMT)
                            .addComponent(jScrollPane1)
                            .addGroup(pnPhieuKhamChiTietLayout.createSequentialGroup()
                                .addComponent(btReset)
                                .addGap(27, 27, 27)
                                .addComponent(jButton1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pnPhieuKhamChiTietLayout.setVerticalGroup(
            pnPhieuKhamChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPhieuKhamChiTietLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnPhieuKhamChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btShow)
                    .addComponent(txtMaBenhNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(20, 20, 20)
                .addGroup(pnPhieuKhamChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(23, 23, 23)
                .addGroup(pnPhieuKhamChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCMT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(pnPhieuKhamChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnPhieuKhamChiTietLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnPhieuKhamChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnPhieuKhamChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnPhieuKhamChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnPhieuKhamChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btHoanThanh)
                        .addComponent(btReset)
                        .addComponent(btHome)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnPhieuKhamChiTiet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnPhieuKhamChiTiet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnPhieuKhamChiTiet.getAccessibleContext().setAccessibleName("Phiếu Xét Nghiệm");

        getAccessibleContext().setAccessibleName("Phiếu Xét Nghiệm");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btShowActionPerformed
        String maBN = this.txtMaBenhNhan.getText();
        if (maBN.length()==0||maBN.length()>6) {
            JOptionPane.showMessageDialog(this,"Mã Bệnh Nhân Không Hợp Lệ","Thông Báo",1);
            return;
        };
        PreparedStatement ps = DBConnection.ThucThiTruyVan("select * from benhnhan where maBenhNhan "
                + "like '"+maBN+"'");
        try {
            ResultSet rs = ps.executeQuery();
            if(!rs.next()){
                JOptionPane.showMessageDialog(this,"Không Có Bệnh Nhân Này","Lỗi !",0);
                return;
            };
        this.txtName.setText(rs.getString("tenBenhNhan"));
        this.txtCMT.setText(rs.getString("soCMND"));
//        ps = DBConnection.ThucThiTruyVan("select * from phieuKhamChiTiet where maBenhNhan "
//                + "like '"+maBN+"'");
//        this.txtChiSoSucKhoe.setText(rs.getString(5));
//        this.txtKetLuan.setText(rs.getString(6));
//        this.txtYeuCau.setText(rs.getString(7));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex, "Lỗi !",0);
        }
        
    }//GEN-LAST:event_btShowActionPerformed

    private void txtMaBenhNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaBenhNhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaBenhNhanActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetActionPerformed
        this.txtMaBenhNhan.setText(null);
        this.txtName.setText(null);
        this.txtCMT.setText(null);
        this.txtChiSoSucKhoe.setText(null);
        this.txtKetLuan.setText(null);
        this.txtYeuCau.setText(null);
    }//GEN-LAST:event_btResetActionPerformed

    private void btHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHomeActionPerformed
        Jfr_HomePage jfr = new Jfr_HomePage();
        jfr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btHomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Jfr_phieuXetNghiem_Edit jfr = new Jfr_phieuXetNghiem_Edit();
        jfr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btHoanThanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHoanThanhActionPerformed
        boolean flag = true;
        if (this.txtMaBenhNhan.getText().length()==0) flag = false;
        if (this.txtName.getText().length()==0) flag = false;
        if (this.txtChiSoSucKhoe.getText().length()==0) flag = false;
        if (this.txtKetLuan.getText().length()==0) flag = false;
        if (this.txtYeuCau.getText().length()==0) flag = false;
        if (!flag) {
            JOptionPane.showMessageDialog(this,"Chưa Đủ Thông Tin","Lỗi !",0);
            return;
        }
        // Get Mã PKCT
        int numXetNghiem=0;
        PreparedStatement ps = DBConnection.ThucThiTruyVan("select * from phieukhamchitiet");
        try {
            ResultSet rs = ps.executeQuery();
            while (rs.next()) numXetNghiem++;
            numXetNghiem++;
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex, "Lỗi !",0);
        };
        // Ngay
        String ngay ="";
        Date dNow = new Date();
        SimpleDateFormat ft = new SimpleDateFormat ("yyyy-MM-dd");
        ngay = ft.format(dNow);
        String maPhieuKham="";
        ps = DBConnection.ThucThiTruyVan("select * from phieukham "
            + "where maBenhNhan like '"+this.txtMaBenhNhan.getText()+"'");
        try {
            ResultSet rs = ps.executeQuery();
            rs.next();
            maPhieuKham = rs.getString(1);
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, e, "Lỗi",0);
        }
        m_XetNghiem m = new m_XetNghiem();
        m.setMaXetNghiem(String.valueOf(numXetNghiem));
        m.setMaBenhNhan(this.txtMaBenhNhan.getText());
        m.setMaNhanVien(maNhanVien);
        m.setNgayKham(ngay);
        m.setChiSoSucKhoe(this.txtChiSoSucKhoe.getText());
        m.setKetLuan(this.txtKetLuan.getText());
        m.setYeuCau(this.txtYeuCau.getText());
        m.setMaPhieuKham(maPhieuKham);
        
        System.out.println("ma Xet Nghiem: "+numXetNghiem);
        System.out.println("ma Benh Nhan: "+this.txtMaBenhNhan.getText());
        System.out.println("ma Nhan Vien: "+maNhanVien);
        System.out.println("ma Ngay Kham: "+ngay);
        System.out.println("ma Chi So Suc Khoe: "+this.txtChiSoSucKhoe.getText());
        System.out.println("ma Ket Luan: "+this.txtKetLuan.getText());
        System.out.println("ma Yeu CDau: "+this.txtYeuCau.getText());
        System.out.println("ma ma Phieu Kham: "+maPhieuKham);
        
        
        c_XetNghiem c = new c_XetNghiem();
        c.insertPhieuKham(m);
        if (c.f){
            if (JOptionPane.showConfirmDialog(this, "Có Muốn In Phiếu Khám ??", "Thông Báo", 1)==0){
                Printer p = new Printer();
                p.inPKCT(String.valueOf(numXetNghiem),this.maNhanVien);
                JOptionPane.showMessageDialog(this, "In Xong, Kết Thúc Phiên Khám", "Thông Báo", 1);
        }
    }//GEN-LAST:event_btHoanThanhActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jfr_phieuXetNghiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jfr_phieuXetNghiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jfr_phieuXetNghiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jfr_phieuXetNghiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jfr_phieuXetNghiem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btHoanThanh;
    private javax.swing.JButton btHome;
    private javax.swing.JButton btReset;
    private javax.swing.JButton btShow;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbNhanVien;
    private javax.swing.JPanel pnPhieuKhamChiTiet;
    private javax.swing.JTextField txtCMT;
    private javax.swing.JTextArea txtChiSoSucKhoe;
    private javax.swing.JTextArea txtKetLuan;
    private javax.swing.JTextField txtMaBenhNhan;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextArea txtYeuCau;
    // End of variables declaration//GEN-END:variables
}
