/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Connection.DBConnection;
import Controller.c_XetNghiem;
import Model.m_XetNghiem;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Controller.c_XetNghiem;
import java.text.SimpleDateFormat;
import java.util.Date;
import Controller.UpdateTable;
/**
 *
 * @author user
 */
public class Jfr_phieuXetNghiem_Edit extends javax.swing.JFrame {

    /**
     * Creates new form Jfr_phieuXetNghiem
     */
    String maNhanVien = Jfr_login.maNhanVien;
    
    String maPhieuKhamChiTiet;
    String maPhieuKham;
    
    public Jfr_phieuXetNghiem_Edit() {
        initComponents();
        UpdateTable.loadData("select maPhieuKhamChiTiet as 'Mã Phiếu Khám Chi Tiết',"
                + " maBenhNhan as 'Mã Bệnh Nhân',"
                + " ngayKham as 'Ngày Khám (Năm-Tháng-Ngày)',"
                + " chiSoSucKhoe as 'Chỉ Số Sức Khỏe',"
                + " ketLuan as 'Kết Luận',"
                + " yeuCau as 'Yêu Cầu',"
                + " maPhieuKham as 'Mã Phiếu Khám' from phieukhamchitiet where maNhanVien like N'"+this.maNhanVien+"'", tbXetNghiem);
        PreparedStatement ps = DBConnection.ThucThiTruyVan("select * from nhanvien "
                + "where maNhanVien like '"+maNhanVien+"'");
        try{
            ResultSet rs = ps.executeQuery();
            rs.next();
            this.lbNhanVien.setText(rs.getString(5)+": "+rs.getString(2)+" - Mã NV: "+maNhanVien);
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex, "Lỗi !",0);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btShow = new javax.swing.JButton();
        txtMaBenhNhan = new javax.swing.JTextField();
        txtNgayKham = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtChiSoSucKhoe = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtKetLuan = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtYeuCau = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        btHoanThanh = new javax.swing.JButton();
        btReset = new javax.swing.JButton();
        lbNhanVien = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMaXetNghiem = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btGenerate = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbXetNghiem = new javax.swing.JTable();
        btBack = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMaPhieuKham = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "QL Khám Chi Tiết", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N

        btShow.setBackground(new java.awt.Color(204, 204, 255));
        btShow.setText("Hiển Thị");
        btShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btShowActionPerformed(evt);
            }
        });

        txtMaBenhNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaBenhNhanActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Mã BN : ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Ngày Khám");

        txtChiSoSucKhoe.setColumns(20);
        txtChiSoSucKhoe.setRows(5);
        jScrollPane1.setViewportView(txtChiSoSucKhoe);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Chỉ Số");

        txtKetLuan.setColumns(20);
        txtKetLuan.setRows(5);
        jScrollPane2.setViewportView(txtKetLuan);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Kết Luận :");

        txtYeuCau.setColumns(20);
        txtYeuCau.setRows(5);
        jScrollPane3.setViewportView(txtYeuCau);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Yêu Cầu :");

        btHoanThanh.setBackground(new java.awt.Color(204, 204, 255));
        btHoanThanh.setText("Hoàn Thành");
        btHoanThanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHoanThanhActionPerformed(evt);
            }
        });

        btReset.setBackground(new java.awt.Color(204, 204, 255));
        btReset.setText("Reset");
        btReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetActionPerformed(evt);
            }
        });

        lbNhanVien.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbNhanVien.setText("jLabel7");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Sức Khỏe :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Mã PKCT");

        btGenerate.setBackground(new java.awt.Color(204, 204, 255));
        btGenerate.setText("Generate");
        btGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGenerateActionPerformed(evt);
            }
        });

        btDelete.setBackground(new java.awt.Color(204, 204, 255));
        btDelete.setText("Xóa");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });

        tbXetNghiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbXetNghiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbXetNghiemMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbXetNghiem);

        btBack.setText("back");
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Mã Phiếu Khám");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("YYYY/MM/DD:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(75, 75, 75))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btGenerate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btShow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMaXetNghiem)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                    .addComponent(txtMaBenhNhan, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                    .addComponent(txtNgayKham)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMaPhieuKham)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btHoanThanh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btReset)
                        .addGap(234, 234, 234)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaXetNghiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(btGenerate))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btShow)
                            .addComponent(txtMaBenhNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNgayKham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(2, 2, 2)
                        .addComponent(jLabel10)
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtMaPhieuKham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btHoanThanh)
                    .addComponent(btReset)
                    .addComponent(btBack))
                .addGap(11, 11, 11)
                .addComponent(lbNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleName("Phiếu Xét Nghiệm");

        getAccessibleContext().setAccessibleName("Phiếu Xét Nghiệm");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btShowActionPerformed
        String maBN = this.txtMaBenhNhan.getText();
        if (maBN.length()==0||maBN.length()>6) {
            JOptionPane.showMessageDialog(this,"Mã Bệnh Nhân Không Hợp Lệ","Thông Báo",1);
            return;
        };
        PreparedStatement ps = DBConnection.ThucThiTruyVan("select * from benhnhan where maBenhNhan "
                + "like '"+maBN+"'");
        try {
            ResultSet rs = ps.executeQuery();
            if(!rs.next()){
                JOptionPane.showMessageDialog(this,"Không Có Bệnh Nhân Này","Lỗi !",0);
                return;
            };
//        this.txtNgayKham.setText(rs.getString("soCMND"));
//        ps = DBConnection.ThucThiTruyVan("select * from phieuKhamChiTiet where maBenhNhan "
//                + "like '"+maBN+"'");
//        this.txtChiSoSucKhoe.setText(rs.getString(5));
//        this.txtKetLuan.setText(rs.getString(6));
//        this.txtYeuCau.setText(rs.getString(7));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex, "Lỗi !",0);
        }
        
    }//GEN-LAST:event_btShowActionPerformed

    private void txtMaBenhNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaBenhNhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaBenhNhanActionPerformed

    private void btGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGenerateActionPerformed
        int numXetNghiem=0;
        PreparedStatement ps = DBConnection.ThucThiTruyVan("select * from phieukhamchitiet");
        try {
            ResultSet rs = ps.executeQuery();
            while (rs.next()) numXetNghiem++;
            numXetNghiem++;
            this.txtMaXetNghiem.setText(String.valueOf(numXetNghiem));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex, "Lỗi !",0);
        }
    }//GEN-LAST:event_btGenerateActionPerformed

    private void btResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetActionPerformed
        this.txtMaXetNghiem.setText(null);
        this.txtMaBenhNhan.setText(null);
        //this.txtMaNhanVien.setText(null);
        this.txtNgayKham.setText(null);
        this.txtChiSoSucKhoe.setText(null);
        this.txtKetLuan.setText(null);
        this.txtYeuCau.setText(null);
        this.txtMaPhieuKham.setText(null);
    }//GEN-LAST:event_btResetActionPerformed

    private void btHoanThanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHoanThanhActionPerformed
        boolean flag = true;
        if (this.txtMaXetNghiem.getText().length()==0) flag = false;
        if (this.txtMaBenhNhan.getText().length()==0) flag = false;
        //if (this.txtMaNhanVien.getText().length()==0) flag = false;
        if (this.txtNgayKham.getText().length()==0) flag = false;
        if (this.txtChiSoSucKhoe.getText().length()==0) flag = false;
        if (this.txtKetLuan.getText().length()==0) flag = false;
        if (this.txtYeuCau.getText().length()==0) flag = false;
        if (this.txtMaPhieuKham.getText().length()==0) flag = false;
        if (!flag) {
            JOptionPane.showMessageDialog(this,"Chưa Đủ Thông Tin","Lỗi !",0);
            return;
        }
        // Ngay
        
        m_XetNghiem m = new m_XetNghiem();
        m.setMaXetNghiem(this.txtMaXetNghiem.getText());
        m.setMaBenhNhan(this.txtMaBenhNhan.getText());
        m.setMaNhanVien(this.maNhanVien);
        m.setNgayKham(this.txtNgayKham.getText());
        m.setChiSoSucKhoe(this.txtChiSoSucKhoe.getText());
        m.setKetLuan(this.txtKetLuan.getText());
        m.setYeuCau(this.txtYeuCau.getText());
        m.setMaPhieuKham(this.txtMaPhieuKham.getText());
        c_XetNghiem c = new c_XetNghiem();
        
        c.updatePhieuKham(m, maPhieuKhamChiTiet);
        UpdateTable.loadData("select * from phieukhamchitiet where maNhanVien like N'"+this.maNhanVien+"'", tbXetNghiem);
        
//        System.out.println(m.getMaXetNghiem());
//        System.out.println(m.getMaBenhNhan());
//        System.out.println(m.getMaNhanVien());
//        System.out.println(m.getNgayKham());
//        System.out.println(m.getChiSoSucKhoe());
//        System.out.println(m.getKetLuan());
//        System.out.println(m.getYeuCau());
//        System.out.println(m.getMaPhieuKham());
        
//        System.out.println("====");
        
    }//GEN-LAST:event_btHoanThanhActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        String maPhieuKhamChiTiet = this.txtMaXetNghiem.getText();
        if (JOptionPane.showConfirmDialog(this, "Xóa Phiếu Khám Chi Tiết Này ? ", "Thông Báo !",0)==0){
            c_XetNghiem c = new c_XetNghiem();
            c.deletePhieuKham(maPhieuKhamChiTiet);
            UpdateTable.loadData("select * from phieuKhamChiTiet", tbXetNghiem);
        }
    }//GEN-LAST:event_btDeleteActionPerformed

    private void tbXetNghiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbXetNghiemMouseClicked
        int row = this.tbXetNghiem.getSelectedRow();
        maPhieuKhamChiTiet = this.tbXetNghiem.getModel().getValueAt(row,0).toString();
        try {
            PreparedStatement ps = DBConnection.ThucThiTruyVan("select * from phieuKhamChiTiet where "
                    + "maPhieuKhamChiTiet like '"+maPhieuKhamChiTiet+"'");
            ResultSet rs = ps.executeQuery();
            rs.next();
            this.txtMaXetNghiem.setText(rs.getString(1));
            this.txtMaBenhNhan.setText(rs.getString(2));
            //this.txtMaNhanVien.setText(maNhanVien);
            this.txtNgayKham.setText(rs.getString(4));
            this.txtChiSoSucKhoe.setText(rs.getString(5));
            this.txtKetLuan.setText(rs.getString(6));
            this.txtYeuCau.setText(rs.getString(7));
            this.txtMaPhieuKham.setText(rs.getString(8));
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e, "Lỗi !", 0);
        }
    }//GEN-LAST:event_tbXetNghiemMouseClicked

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        Jfr_phieuXetNghiem jfr = new Jfr_phieuXetNghiem();
        jfr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jfr_phieuXetNghiem_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jfr_phieuXetNghiem_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jfr_phieuXetNghiem_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jfr_phieuXetNghiem_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jfr_phieuXetNghiem_Edit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBack;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btGenerate;
    private javax.swing.JButton btHoanThanh;
    private javax.swing.JButton btReset;
    private javax.swing.JButton btShow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbNhanVien;
    private javax.swing.JTable tbXetNghiem;
    private javax.swing.JTextArea txtChiSoSucKhoe;
    private javax.swing.JTextArea txtKetLuan;
    private javax.swing.JTextField txtMaBenhNhan;
    private javax.swing.JTextField txtMaPhieuKham;
    private javax.swing.JTextField txtMaXetNghiem;
    private javax.swing.JTextField txtNgayKham;
    private javax.swing.JTextArea txtYeuCau;
    // End of variables declaration//GEN-END:variables
}
