/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.QuanLyNhanVien;
import Controller.NhanVien;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Jfr_QuanLyPhongKham extends javax.swing.JFrame {

    /**
     * Creates new form Jfr_QuanLyPhongKham
     */
    DefaultTableModel model;
    private ArrayList<NhanVien> list;
    private String maNVCu;
    private String maUserDangNhap;

    public String getMaUserDangNhap() {
        return maUserDangNhap;
    }

    public void setMaUserDangNhap(String maUserDangNhap) {
        this.maUserDangNhap = maUserDangNhap;
    }
    
    public Jfr_QuanLyPhongKham() {
        try {
            initComponents();
            this.setLocationRelativeTo(null);
            list = new QuanLyNhanVien().getListNhanVien();
            model = (DefaultTableModel) jTable_NhanVien.getModel();
            model.setColumnIdentifiers(new Object[]{
                "STT","Mã NV","Họ Tên","Ngày Sinh","Giới tính","Chức Vụ","Địa Chỉ","Số Điện Thoại","Email","Số CMND","Password"
            });
            
            showTable();
            setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            setLocationRelativeTo(null);
        } catch (SQLException ex) {
            Logger.getLogger(Jfr_QuanLyPhongKham.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public Jfr_QuanLyPhongKham(String maNhanVien) {
        try {
            initComponents();
            this.setLocationRelativeTo(null);
            this.setMaUserDangNhap(maNhanVien);
            list = new QuanLyNhanVien().getListNhanVien();
            model = (DefaultTableModel) jTable_NhanVien.getModel();
            model.setColumnIdentifiers(new Object[]{
                "STT","Mã NV","Họ Tên","Ngày Sinh","Giới tính","Chức Vụ","Địa Chỉ","Số Điện Thoại","Email","Số CMND","Password"
            });
            
            showTable();
            setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        } catch (SQLException ex) {
            Logger.getLogger(Jfr_QuanLyPhongKham.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton_themNhanVien = new javax.swing.JButton();
        jButton_xoaNhanVien = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_NhanVien = new javax.swing.JTable();
        txtTimKiem = new javax.swing.JTextField();
        jButton_timKiemNhanVien = new javax.swing.JButton();
        jButton_suaNhanVien = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaNhanVien = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNgaySinh = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtChucVu = new javax.swing.JComboBox<String>();
        jLabel6 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSoDienThoai = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtSoCMND = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtGioiTinh = new javax.swing.JComboBox<String>();
        jButton_reset = new javax.swing.JButton();
        jButton_LuuNhanVien = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        txtHome = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quản lý phòng khám", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jButton_themNhanVien.setText("Thêm nhân viên");
        jButton_themNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_themNhanVienActionPerformed(evt);
            }
        });

        jButton_xoaNhanVien.setText("Xóa nhân viên");
        jButton_xoaNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_xoaNhanVienActionPerformed(evt);
            }
        });

        jTable_NhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã NV", "Họ Tên", "Ngày Sinh", "Giới tinh", "Chức Vụ", "Địa Chỉ", "Số Điện Thoại", "Email", "Số CMND"
            }
        ));
        jTable_NhanVien.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTable_NhanVienAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jTable_NhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_NhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_NhanVien);

        jButton_timKiemNhanVien.setText("Tìm kiếm");
        jButton_timKiemNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_timKiemNhanVienActionPerformed(evt);
            }
        });

        jButton_suaNhanVien.setText("Sửa nhân viên");
        jButton_suaNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_suaNhanVienActionPerformed(evt);
            }
        });

        jLabel1.setText("Mã NV");

        jLabel2.setText("Họ Tên");

        jLabel4.setText("Ngày Sinh");

        txtNgaySinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgaySinhActionPerformed(evt);
            }
        });

        jLabel5.setText("Chức Vụ");

        txtChucVu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nhân viên lễ tân", "Bác sĩ đa khoa", "Bác sĩ chuyên khoa", "Nhân viên xét nghiệm", "Dược sĩ" }));

        jLabel6.setText("Địa chỉ");

        jLabel7.setText("Số ĐT");

        txtSoDienThoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoDienThoaiActionPerformed(evt);
            }
        });

        jLabel8.setText("Email");

        jLabel9.setText("Số CMND");

        jLabel10.setText("Giới tính");

        txtGioiTinh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nam", "Nữ" }));

        jButton_reset.setText("Reset");
        jButton_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_resetActionPerformed(evt);
            }
        });

        jButton_LuuNhanVien.setText("Lưu");
        jButton_LuuNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LuuNhanVienActionPerformed(evt);
            }
        });

        jLabel3.setText("Nhập theo định dạng yyyy-mm-dd");

        jLabel11.setText("Password");

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        txtHome.setText("Home");
        txtHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtHomeMouseClicked(evt);
            }
        });
        txtHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHomeActionPerformed(evt);
            }
        });

        btnThongKe.setText("Thống kê hoạt động phòng khám");
        btnThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThongKeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMaNhanVien)
                                    .addComponent(txtHoTen, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSoCMND)
                                    .addComponent(txtNgaySinh)
                                    .addComponent(txtChucVu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDiaChi)
                                    .addComponent(txtSoDienThoai)
                                    .addComponent(txtEmail)
                                    .addComponent(txtGioiTinh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                    .addComponent(txtPassword))))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnThongKe)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtTimKiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_timKiemNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_themNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(jButton_suaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jButton_LuuNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_xoaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtHome))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_timKiemNhanVien)
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnThongKe))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtSoCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_themNhanVien)
                        .addComponent(jButton_reset))
                    .addComponent(jButton_suaNhanVien)
                    .addComponent(jButton_xoaNhanVien)
                    .addComponent(jButton_LuuNhanVien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(txtHome))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_LuuNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LuuNhanVienActionPerformed
        // TODO add your handling code here:
        /*int r = jTable_NhanVien.getSelectedRow();
        NhanVien nv = new NhanVien();
        nv.setMaNhanVien(txtMaNhanVien.getText());
        nv.setHoTen(txtHoTen.getText());
        nv.setNgaySinh(txtNgaySinh.getText());
        if(txtGioiTinh.getSelectedItem().toString().equalsIgnoreCase("Nam"))
        {
            nv.setGioiTinh(1);
        }else
        {
            nv.setGioiTinh(0);
        }

        nv.setChucVu(txtChucVu.getSelectedItem().toString());
        nv.setDiaChi(txtDiaChi.getText());
        nv.setSoDienThoai(txtSoDienThoai.getText());
        nv.setEmail(txtEmail.getText());
        nv.setSoCMND(txtSoCMND.getText());

        model.setValueAt(nv.getMaNhanVien(), r, 1);
        model.setValueAt(nv.getHoTen(), r, 2);
        model.setValueAt(nv.getNgaySinh(), r, 3);
        if(nv.getGioiTinh() == 1)
        {
            model.setValueAt("Nam", r, 4);
        }else
        {
            model.setValueAt("Nữ", r, 4);
        }

        model.setValueAt(nv.getChucVu(), r, 5);
        model.setValueAt(nv.getDiaChi(), r, 6);
        model.setValueAt(nv.getSoDienThoai(), r, 7);
        model.setValueAt(nv.getEmail(), r, 8);
        model.setValueAt(nv.getSoCMND(), r, 9);*/
        String error="";
        NhanVien nv = new NhanVien();
        if(txtMaNhanVien.getText().equalsIgnoreCase(""))
        {
            error += "Không để trống mã nhân viên\n";
        }
        
        if(txtHoTen.getText().equalsIgnoreCase(""))
        {
            error += "Không để trống họ tên\n";
        }
        
        if(txtNgaySinh.getText().equalsIgnoreCase(""))
        {
            error += "Không để trống ngày sinh\n";
        }
        
        
        if(txtDiaChi.getText().equalsIgnoreCase(""))
        {
            error += "Không để trống địa chỉ\n";
        }
        
        if(txtSoDienThoai.getText().equalsIgnoreCase(""))
        {
             error += "Không để trống số điện thoại\n";
        }
        
        if(txtEmail.getText().equalsIgnoreCase(""))
        {
            error += "Không để trống email\n";
        }
        
        if(txtSoCMND.getText().equalsIgnoreCase(""))
        {
            error += "Không để trống số CMND\n";
        }
        
        if(txtPassword.getText().equalsIgnoreCase(""))
        {
            error += "Không để trống số password\n";
        }
        
        if(txtNgaySinh.getText().matches("[0-9]{4}-[0-9]{2}-[0-9]{2}") == false)
        {
            error += "Không nhập đúng định dạng yyyy-mm-dd\n";
        }
       
        if(error.equalsIgnoreCase(""))
        {
            try {
                nv.setMaNhanVien(txtMaNhanVien.getText());
                nv.setHoTen(txtHoTen.getText());
                String ngaySinh = txtNgaySinh.getText();
                SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
                Date date = formatter.parse(ngaySinh);
                nv.setNgaySinh(date);
                nv.setGioiTinh(txtGioiTinh.getSelectedItem().toString());
                
                nv.setChucVu(txtChucVu.getSelectedItem().toString());
                nv.setDiaChi(txtDiaChi.getText());
                nv.setSoDienThoai(txtSoDienThoai.getText());
                nv.setEmail(txtEmail.getText());
                nv.setSoCMND(txtSoCMND.getText());
                nv.setPassword(txtPassword.getText());
                if(new QuanLyNhanVien().updateNhanVien(nv,maNVCu))
                {
                    JOptionPane.showMessageDialog(rootPane, "Chỉnh sửa thông tin nhân viên thành công");
                    this.setVisible(false);
                    new Jfr_QuanLyPhongKham().setVisible(true);
                }else
                {
                    JOptionPane.showMessageDialog(rootPane, "Chỉnh sửa thông tin nhân viên không thành công");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Jfr_QuanLyPhongKham.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(Jfr_QuanLyPhongKham.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else
        {
            JOptionPane.showMessageDialog(rootPane, error);
        }
        
    }//GEN-LAST:event_jButton_LuuNhanVienActionPerformed

    private void jButton_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_resetActionPerformed
        // TODO add your handling code here:
        txtMaNhanVien.setText("");
        txtHoTen.setText("");
        txtNgaySinh.setText("");
        txtDiaChi.setText("");
        txtSoDienThoai.setText("");
        txtEmail.setText("");
        txtSoCMND.setText("");
        txtPassword.setText("");
    }//GEN-LAST:event_jButton_resetActionPerformed

    private void txtSoDienThoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoDienThoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoDienThoaiActionPerformed

    private void txtNgaySinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgaySinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgaySinhActionPerformed

    private void jButton_suaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_suaNhanVienActionPerformed
        // TODO add your handling code here:
        int r = jTable_NhanVien.getSelectedRow();
        if(r != -1)
        {
            maNVCu = model.getValueAt(r, 1).toString();
            txtMaNhanVien.setText(model.getValueAt(r, 1).toString());
            txtHoTen.setText(model.getValueAt(r, 2).toString());
            txtNgaySinh.setText(model.getValueAt(r, 3).toString());
            if(model.getValueAt(r, 4).toString().equalsIgnoreCase("Nữ"))
            {
                txtGioiTinh.setSelectedItem("Nữ");
            }
            else
            {
                txtGioiTinh.setSelectedItem("Nam");
            }
            txtChucVu.setSelectedItem(model.getValueAt(r, 5).toString());
            txtDiaChi.setText(model.getValueAt(r, 6).toString());
            txtSoDienThoai.setText(model.getValueAt(r, 7).toString());
            txtEmail.setText(model.getValueAt(r, 8).toString());
            txtSoCMND.setText(model.getValueAt(r, 9).toString());
            txtPassword.setText(model.getValueAt(r, 10).toString());
        }
    }//GEN-LAST:event_jButton_suaNhanVienActionPerformed

    private void jButton_timKiemNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_timKiemNhanVienActionPerformed
        try {
            // TODO add your handling code here:
            String hoTen = txtTimKiem.getText();
            model.setRowCount(0);
            list = null;
            list = new QuanLyNhanVien().timKiem(hoTen);
            showTable();
        } catch (SQLException ex) {
            Logger.getLogger(Jfr_QuanLyPhongKham.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_timKiemNhanVienActionPerformed

    private void jTable_NhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_NhanVienMouseClicked

    }//GEN-LAST:event_jTable_NhanVienMouseClicked

    private void jTable_NhanVienAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTable_NhanVienAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable_NhanVienAncestorAdded

    private void jButton_xoaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_xoaNhanVienActionPerformed
        try {
            // TODO add your handling code here:
            String maNhanVien = JOptionPane.showInputDialog("Mời bạn nhập mã nhân viên");
            if(new QuanLyNhanVien().deleteNhanVien(maNhanVien)){
                JOptionPane.showMessageDialog(rootPane, "Xóa thành công !!!");
                this.setVisible(false);
                new Jfr_QuanLyPhongKham().setVisible(true);
            }else
            {
                JOptionPane.showMessageDialog(rootPane, "Mã nhân viên không hợp lê");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Jfr_QuanLyPhongKham.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_xoaNhanVienActionPerformed

    private void jButton_themNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_themNhanVienActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Jfr_ThemNhanVien().setVisible(true);
    }//GEN-LAST:event_jButton_themNhanVienActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHomeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Jfr_HomePage().setVisible(true);
    }//GEN-LAST:event_txtHomeActionPerformed

    private void btnThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongKeMouseClicked
        Jfr_thongKe thongKe = new Jfr_thongKe();
        thongKe.show();
    }//GEN-LAST:event_btnThongKeMouseClicked

    private void txtHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHomeMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtHomeMouseClicked
    public void showTable()
    {
        int i=1;
        for(NhanVien nv: list)
        {
           
            model.addRow(new Object[]{
                i++,nv.getMaNhanVien(),nv.getHoTen(),nv.getNgaySinh(),nv.getGioiTinh(),nv.getChucVu(),nv.getDiaChi(),nv.getSoDienThoai(),nv.getEmail(),nv.getSoCMND(),nv.getPassword()
            });
        }
    }    
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jfr_QuanLyPhongKham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jfr_QuanLyPhongKham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jfr_QuanLyPhongKham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jfr_QuanLyPhongKham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jfr_QuanLyPhongKham().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton jButton_LuuNhanVien;
    private javax.swing.JButton jButton_reset;
    private javax.swing.JButton jButton_suaNhanVien;
    private javax.swing.JButton jButton_themNhanVien;
    private javax.swing.JButton jButton_timKiemNhanVien;
    private javax.swing.JButton jButton_xoaNhanVien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_NhanVien;
    private javax.swing.JComboBox<String> txtChucVu;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JComboBox<String> txtGioiTinh;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JButton txtHome;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtSoCMND;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
